server:
  port: 8877
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/location/**
          filters:
            - name: Retry
              args:
                retries: 3
        - id: astronomical-object-service
          uri: lb://astronomical-object-service
          predicates:
            - Path=/astronomical/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
        - id: location-service
          uri: lb://forecast-service
          predicates:
            - Path=/forecast/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5