server:
  port: 0
spring:
  application:
    name: calculator-service
  config:
    import: optional:configserver:http://localhost:8081
  profiles:
    active: development
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}