server:
  port: 0
spring:
  application:
    name: calculator-service
  config:
    import: optional:configserver:http://localhost:8444
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}